// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: live.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	GetLiveStream(ctx context.Context, opts ...grpc.CallOption) (StreamingService_GetLiveStreamClient, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) GetLiveStream(ctx context.Context, opts ...grpc.CallOption) (StreamingService_GetLiveStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[0], "/pb.StreamingService/GetLiveStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceGetLiveStreamClient{stream}
	return x, nil
}

type StreamingService_GetLiveStreamClient interface {
	Send(*StreamingRequest) error
	Recv() (*StreamingResponse, error)
	grpc.ClientStream
}

type streamingServiceGetLiveStreamClient struct {
	grpc.ClientStream
}

func (x *streamingServiceGetLiveStreamClient) Send(m *StreamingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingServiceGetLiveStreamClient) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility
type StreamingServiceServer interface {
	GetLiveStream(StreamingService_GetLiveStreamServer) error
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamingServiceServer struct {
}

func (UnimplementedStreamingServiceServer) GetLiveStream(StreamingService_GetLiveStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLiveStream not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_GetLiveStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServiceServer).GetLiveStream(&streamingServiceGetLiveStreamServer{stream})
}

type StreamingService_GetLiveStreamServer interface {
	Send(*StreamingResponse) error
	Recv() (*StreamingRequest, error)
	grpc.ServerStream
}

type streamingServiceGetLiveStreamServer struct {
	grpc.ServerStream
}

func (x *streamingServiceGetLiveStreamServer) Send(m *StreamingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingServiceGetLiveStreamServer) Recv() (*StreamingRequest, error) {
	m := new(StreamingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLiveStream",
			Handler:       _StreamingService_GetLiveStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "live.proto",
}
